### ISSUE TITLE
Connection closed when I initiate connection from client with the hot key

### ISSUE THREAD

**Issue by curiousplaymedia** [sidit77/InputShareUSB#5]
Hi, I have the client running on a windows machine and RPi zero connected to fedora workstation as a slave USB. Client machine able to initiate connection but then when I initiate Remote access with the hotkey on the windows client I see the following trace on the RPI 0.

`DEBUG inputshare_server: Attempting to bind 0.0.0.0:60067
DEBUG inputshare_server::configfs: Enabling HID device
DEBUG configfs_input_processor{tess_factor=5 timeout=None}: inputshare_server: Starting configfs processor
TRACE monitor_daemon: inputshare_server::util: Announce("inputshare server._inputshare._udp.local.", "[192.168.86.191]")
DEBUG drive{id=0}: quinn_proto::connection: ECN not acknowledged by peer
DEBUG handle_connection{addrs="192.168.86.183:51404"}: inputshare_server: Established connection
ERROR configfs_input_processor{tess_factor=5 timeout=None}: inputshare_server: Could not write hid command: Cannot send after transport endpoint shutdown (os error 108)
DEBUG configfs_input_processor{tess_factor=5 timeout=None}: inputshare_server: Stopping configfs processor
DEBUG configfs_input_processor{tess_factor=5 timeout=None}: inputshare_server::configfs: Disabling HID device
ERROR inputshare_server: Connection crashed!
The input processor seems to be gone
`

![Screenshot from 2024-09-16 11-44-51](https://github.com/user-attachments/assets/65acd4c6-9f55-4fe9-bba9-90118fcd66ed)

**Comment by curiousplaymedia** [comment]
Looks like changing the cable did the trick.one out of 6 cables worked.  TY

**Comment by sidit77** [comment]
Yeah, it's the same issue as https://github.com/sidit77/InputShareUSB/issues/4. It's quite annoying how different USB cables can be.
